// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package ar.edu.itba.pod.rmi.def.e2;

public final class GenericServiceImpl_Stub
    extends java.rmi.server.RemoteStub
    implements ar.edu.itba.pod.rmi.def.e2.GenericService
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_addToServiceQueue_0;
    private static java.lang.reflect.Method $method_addVisit_1;
    private static java.lang.reflect.Method $method_echo_2;
    private static java.lang.reflect.Method $method_getFirstInServiceQueue_3;
    private static java.lang.reflect.Method $method_getVisitCount_4;
    private static java.lang.reflect.Method $method_isServiceQueueEmpty_5;
    private static java.lang.reflect.Method $method_toUpper_6;
    
    static {
	try {
	    $method_addToServiceQueue_0 = ar.edu.itba.pod.rmi.def.e2.GenericService.class.getMethod("addToServiceQueue", new java.lang.Class[] {java.lang.String.class});
	    $method_addVisit_1 = ar.edu.itba.pod.rmi.def.e2.GenericService.class.getMethod("addVisit", new java.lang.Class[] {});
	    $method_echo_2 = ar.edu.itba.pod.rmi.def.e2.GenericService.class.getMethod("echo", new java.lang.Class[] {java.lang.String.class});
	    $method_getFirstInServiceQueue_3 = ar.edu.itba.pod.rmi.def.e2.GenericService.class.getMethod("getFirstInServiceQueue", new java.lang.Class[] {});
	    $method_getVisitCount_4 = ar.edu.itba.pod.rmi.def.e2.GenericService.class.getMethod("getVisitCount", new java.lang.Class[] {});
	    $method_isServiceQueueEmpty_5 = ar.edu.itba.pod.rmi.def.e2.GenericService.class.getMethod("isServiceQueueEmpty", new java.lang.Class[] {});
	    $method_toUpper_6 = ar.edu.itba.pod.rmi.def.e2.GenericService.class.getMethod("toUpper", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public GenericServiceImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of addToServiceQueue(String)
    public void addToServiceQueue(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_addToServiceQueue_0, new java.lang.Object[] {$param_String_1}, -5113853115681935375L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of addVisit()
    public void addVisit()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_addVisit_1, null, -7012196872562523857L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of echo(String)
    public java.lang.String echo(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_echo_2, new java.lang.Object[] {$param_String_1}, 5525131960618330777L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getFirstInServiceQueue()
    public java.lang.String getFirstInServiceQueue()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getFirstInServiceQueue_3, null, -2140470255367136213L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getVisitCount()
    public int getVisitCount()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getVisitCount_4, null, 5584180260505249638L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of isServiceQueueEmpty()
    public boolean isServiceQueueEmpty()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_isServiceQueueEmpty_5, null, -7387869053366825373L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of toUpper(String)
    public java.lang.String toUpper(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_toUpper_6, new java.lang.Object[] {$param_String_1}, 2363043733809673265L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
